/// <summary>
/// You are given two strings s and t.
/// String t is generated by random shuffling string s and then add one more letter at
/// a random position.
/// Return the letter that was added to t.
/// </summary>
internal class Program
{
    private static void Main(string[] args)
    {
        FindTheDifference("","y");
        FindTheDifference("abcd", "abcde");

    }

    public static char FindTheDifference(string s, string t)
    {
        for (int i = 0; i < s.Length; i++)
        {
            var index = t.IndexOf(s[i]);
            t = t.Remove(index,1);
        }
        char res = t[0];
        return res;
    }
}